### PR TITLE
make.vcf.R: Fixed matching of chrom to FASTA contig ID & Speeding up VCF creation by reading reference sequence once

### LINKED ISSUE #14: VCF Creation Issue
I have used the following commands to generate reference files (*.nhr, *.nin, and *.nsq files) for VCF creation for both GRCh37/38. 

makeblastdb -in file.fasta -input_type fasta -dbtype nucl

However, when I run the Cluster analysis, I get the following error:

Done analyzing MEIs
Writing VCF file
Loading required package: GenomeInfoDb
Loading required package: GenomicRanges
Error: subscript contains invalid names
Execution halted

This occurs with either reference (37 or 38). 

Any ideas how I could go about troubleshooting this step? 

Thanks in advance

### PR DESCRIPTION
**Pull request by your-highness**
In hs37d5 (and other reference fasta files) the sequence identifiers contain contigID and additional information on this contig:
```bash
>1 dna:chromosome chromosome:GRCh37:1:1:249250621:1
>2 dna:chromosome chromosome:GRCh37:2:1:243199373:1
>3 dna:chromosome chromosome:GRCh37:3:1:198022430:1
...
```
Alignment software, _e.g._ `bwa`, strip additional information because most downstream tools can not deal with spaces in contig IDs. 

This pull request matches read FASTA IDs with the contigs from working BAM file.

Fixes #14

### CODE REVIEW

File: cluster_analysis/bin/SCRAMble.R [hunk 1]
```diff
@@ -106,30 +106,29 @@ if(!no.vcf){
...
+    write.table(make.vcf.header(fa, blastRef), paste0(outFilePrefix, ".vcf"), row.names=F, col.names=F, quote=F)
+
     # get mei results to fixed data frame
-    if(meis){
-      mei.fixed = write.scramble.vcf(winners=mei.winners, blastRef=blastRef,  meis=meis)
-    }else{
-      mei.fixed = NULL
-    }
+    mei.fixed = NULL
+    print(mei.winners)
```
Comment (rebecca810) [inline cluster_analysis/bin/SCRAMble.R:121]: please remove print statement

**Review by rebeccaito — CHANGES_REQUESTED** [review]

**Comment by rebecca810** [comment]
Thanks for the PR! This is a good improvement.

**Review by rebeccaito — APPROVED** [review]
Many thanks for your contributions!

**Comment by ulloaa** [comment]
Hello,

Any idea on when this change will be merged? Ideally, a bug-fixing version would be released as well.

thanks

**Comment by ulloaa** [comment]
Thanks!
